"""
Threat Actor Intelligence Module
Manages threat actor profiles, activities, and assessments
"""

import logging
import sqlite3
from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)


class ThreatActorIntelligence:
    """Manages threat actor profiles and activities"""

    # Comprehensive threat actor database with accurate attributions
    # Data sourced from CISA, MITRE ATT&CK (https://attack.mitre.org/groups/), Mandiant, Recorded Future
    DEFAULT_ACTORS = {
        "Russia": [
            {
                "name": "APT29",
                "mitre_id": "G0016",
                "alias": "Cozy Bear, The Dukes, YTTRIUM, NOBELIUM, Midnight Blizzard, SVR",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Healthcare, Think Tanks, NGOs",
                "target_geo": "US, Europe, NATO members, Ukraine",
                "ttps": "T1190 - Exploit Public-Facing Application, T1083 - File Discovery, T1005 - Data from Local System, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1110 - Brute Force, T1082 - System Information Discovery",
                "associated_malware": "SUNBURST, SUPERNOVA, TEARDROP, RAINBOW, GOLDENROUGE, YTTRIUM",
                "associated_tools": "Cobalt Strike, PowerShell scripts, Mimikatz",
                "first_observed": "2008",
                "description": "Russian SVR (Foreign Intelligence Service) threat group. Responsible for SolarWinds compromise (2020), targeting US government agencies and contractors. Highly sophisticated, uses supply chain attacks.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "APT28",
                "mitre_id": "G0007",
                "alias": "Fancy Bear, Pawn Storm, STRONTIUM, Iron Twilight, Group 74, GRU",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Media, Think Tanks, Energy, Elections",
                "target_geo": "US, Europe, Ukraine, NATO, Caucasus",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1056 - Input Capture, T1082 - System Information Discovery, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1110 - Brute Force, T1005 - Data from Local System, T1048 - Exfiltration Over Alternative Protocol",
                "associated_malware": "Sofacy, XAgent, Sedre, CHOPSTICK, JSSI, STARBLEED",
                "associated_tools": "Cobalt Strike, Metasploit, PowerDuke",
                "first_observed": "2004",
                "description": "Russian GRU Unit 26165. Responsible for 2016 US election hacking, DNC breach, targeting NATO, Ukrainian military. Uses strategic web compromises.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Sandworm Team",
                "mitre_id": "G0034",
                "alias": "Voodoo Bear, Electrum, Quedagh, Iron Viking, BlackEnergy Group, GRU",
                "actor_type": "State-sponsored",
                "motivation": "Sabotage + Espionage + Financial",
                "capabilities": "Advanced Persistent Threat, Destructive Malware",
                "target_sectors": "Energy, Critical Infrastructure, Government, Media, Finance",
                "target_geo": "Ukraine, Europe, US, Georgia",
                "ttps": "T1486 - Data Encrypted for Impact, T1490 - Inhibit System Recovery, T1489 - Service Stop, T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1083 - File Discovery, T1005 - Data from Local System",
                "associated_malware": "NotPetya, Industroyer, BlackEnergy, KillDisk, GreyEnergy, Cyclops Blink, VPNFilter",
                "associated_tools": "Impacket, CrackMapExec",
                "first_observed": "2007",
                "description": "Russian GRU Unit 74455. Responsible for 2015/2016 Ukraine power grid attacks, NotPetya (2017), Paris Olympics attack planning. Destructive wiper attacks.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Turla",
                "mitre_id": "G0010",
                "alias": "Waterbug, Venomous Bear, Krypton",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Research, Academia",
                "target_geo": "US, Europe, Middle East, Asia",
                "ttps": "T1083 - File Discovery, T1082 - System Information Discovery, T1005 - Data from Local System, T1566 - Phishing, T1105 - Ingress Tool Transfer, T1078 - Valid Accounts, T1556 - Credentials from Password Stores, T1089 - Exfiltration Over Alternative Protocol",
                "associated_malware": "Turla, Snake, Uroboros, Gazer, MonkeyEgg, Epic, Toucan",
                "associated_tools": "Cobalt Strike, RPC scanning",
                "first_observed": "2004",
                "description": "Russian KGB-linked group. Targets diplomatic, military, and research institutions. Uses sophisticated rootkits and satellite-based C2.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Gamaredon Group",
                "mitre_id": "G0047",
                "alias": "Armageddon, Primitive Bear, Shuckworm",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Law Enforcement",
                "target_geo": "Ukraine, Georgia, NATO",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1083 - File Discovery, T1005 - Data from Local System, T1105 - Ingress Tool Transfer, T1078 - Valid Accounts",
                "associated_malware": "Gamaredon, Block, ClickOnce-based loaders",
                "associated_tools": "PowerShell Empire, Cobalt Strike",
                "first_observed": "2013",
                "description": "Russian FSB-linked group. Primarily targets Ukrainian government and military. Active throughout Ukraine conflict.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Dragonfly",
                "mitre_id": "G0035",
                "alias": "TEMP.Isotope, DYMALLOY, Berserk Bear, TG-4192, Crouching Yeti, Ghost Blizzard",
                "actor_type": "State-sponsored",
                "motivation": "Espionage, Energy sector targeting",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Energy, Defense, Aviation, Government, ICS",
                "target_geo": "US, Europe, Ukraine, global",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1078 - Valid Accounts, T1059 - Command and Scripting Interpreter, T1083 - File Discovery",
                "associated_malware": "Havex, Blackenergy, Killdisk, Triton,Industroyer",
                "associated_tools": "Metasploit, Cobalt Strike",
                "first_observed": "2010",
                "description": "Russian FSB-linked group. Targeted energy sector, ICS/SCADA systems. Also known as Crouching Yeti. Supply chain attacks via vendor websites.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Fin7",
                "mitre_id": "G0046",
                "alias": "Carbanak, Navigator Group, Carbon Spider, ITG14",
                "actor_type": "Criminal",
                "motivation": "Financial",
                "capabilities": "Organized Crime Group",
                "target_sectors": "Finance, Retail, Hospitality, Healthcare",
                "target_geo": "US, Europe, Russia",
                "ttps": "T1566 - Phishing, T1027 - Obfuscated Files, T1027 - Obfuscated Code or Information, T1059 - Command and Scripting Interpreter, T1005 - Data from Local System, T1082 - System Information Discovery",
                "associated_malware": "Carbanak, Korablin, Cobalt Strike variants",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2013",
                "description": "Financial crime organization. ATM malware, POS scraping, banking trojan activities. Estimated $1B+ stolen. Front company Combi Security.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Ember Bear",
                "mitre_id": "G1003",
                "alias": "UNC2589, Bleeding Bear, DEV-0586, Cadet Blizzard, Frozenvista",
                "actor_type": "State-sponsored",
                "motivation": "Sabotage",
                "capabilities": "Destructive Malware",
                "target_sectors": "Government, Critical Infrastructure, Telecom",
                "target_geo": "Ukraine, Europe, Americas",
                "ttps": "T1486 - Data Encrypted for Impact, T1490 - Inhibit System Recovery, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter",
                "associated_malware": "WhisperGate, Cyclops Blink",
                "associated_tools": "Custom wipers",
                "first_observed": "2020",
                "description": "Russian GRU Unit 29155. Destructive wiper attacks against Ukraine (WhisperGate 2022). Targets telecom and government.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Cobalt Group",
                "mitre_id": "G0080",
                "alias": "GOLD KINGSWOOD, Cobalt Gang, Cobalt Spider",
                "actor_type": "Criminal",
                "motivation": "Financial",
                "capabilities": "Financial theft, ATM hacking",
                "target_sectors": "Finance, Banking, Retail",
                "target_geo": "Eastern Europe, Central Asia, Southeast Asia",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Cobalt Strike, Carbanak",
                "associated_tools": "Cobalt Strike",
                "first_observed": "2016",
                "description": "Financially motivated group targeting banks. ATM systems, card processing, SWIFT. Arrested leader in Spain 2018 but still active.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "Indrik Spider",
                "mitre_id": "G0119",
                "alias": "Evil Corp, Manatee Tempest, DEV-0243, UNC2165",
                "actor_type": "Criminal",
                "motivation": "Financial",
                "capabilities": "Banking Trojan, Ransomware",
                "target_sectors": "Finance, Banking",
                "target_geo": "Global",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Dridex, BitPaymer, WastedLocker",
                "associated_tools": "Custom trojans",
                "first_observed": "2014",
                "description": "Russia-based cybercrime group. Dridex banking Trojan, BitPaymer/WastedLocker ransomware. US sanctions in 2019.",
                "risk_level": "critical",
                "country_region": "EMEA",
                "active": 1,
            },
            {
                "name": "APT44",
                "mitre_id": "G1015",
                "alias": "Cyber Army Russia, Krypton, Russian Hacktivists",
                "actor_type": "Hacktivist",
                "motivation": "Hacktivism + Sabotage",
                "capabilities": "DDoS, Defacement, Data Wiping",
                "target_sectors": "Government, Critical Infrastructure, Media",
                "target_geo": "Ukraine, US, Europe",
                "ttps": "T1486 - Data Encrypted for Impact, T1490 - Inhibit System Recovery, T1498 - Network Denial of Service, T1485 - Destruction",
                "associated_malware": "AwfulShed, Patriks, ransomexx",
                "first_observed": "2022",
                "description": "Pro-Russian hacktivist group conducting wiper attacks and DDoS against Ukraine and Western targets.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
        ],
        "China": [
            {
                "name": "APT41",
                "mitre_id": "G0096",
                "alias": "Winnti, Barium, Wicked Panda, Lead, TG-3390, Ethereal Panda, Blackfly",
                "actor_type": "State-sponsored",
                "motivation": "Espionage + Financial",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Healthcare, Pharma, Gaming, Tech, Defense, Telecom, Education",
                "target_geo": "Global, focus on US/Europe/Southeast Asia",
                "ttps": "T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1082 - System Information Discovery, T1005 - Data from Local System, T1083 - File Discovery, T1105 - Ingress Tool Transfer, T1048 - Exfiltration, T1041 - Exfiltration Over C2",
                "associated_malware": "Winnti, ShadowPad, HTTPTRACE, Spyder, LIFEBOAT, Tonto Team, BISONAL",
                "associated_tools": "Cobalt Strike, Metasploit, Powersploit",
                "first_observed": "2010",
                "description": "Chinese Ministry of State Security (MSS)-linked group. Conducts state espionage and financially-motivated crime. Healthcare targeting notable. Supply chain compromises via gaming software.",
                "risk_level": "critical",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT10",
                "mitre_id": "G0012",
                "alias": "MenuPass, Stone Panda, CVNX, HOPLIGHT",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Government, Tech, Aerospace, Maritime",
                "target_geo": "US, Japan, Korea, India, Europe",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery, T1078 - Valid Accounts, T1105 - Ingress Tool Transfer, T1041 - Exfiltration Over C2",
                "associated_malware": "Chinasch, Tonto,oko, PoisonIvy, KasperAgent, UPPERCUT",
                "associated_tools": "PoisonIvy RAT, Cobalt Strike",
                "first_observed": "2006",
                "description": "Chinese MSS-linked group. Also known as MenuPass. Targets defense contractors, government agencies, and managed service providers.",
                "risk_level": "critical",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT17",
                "mitre_id": "G0025",
                "alias": "Office 31, Honey/My, Tailgater, Deputy Dog",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Government, Think Tanks, Healthcare",
                "target_geo": "US, South Korea, Japan, Taiwan",
                "ttps": "T1566 - Phishing, T1200 - Hardware Additions, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "HyperBro, ASPXSpy, China Chopper, Tonto",
                "associated_tools": "China Chopper, Cobalt Strike",
                "first_observed": "2012",
                "description": "Chinese state-sponsored actor. Targeting defense contractors and government agencies via strategic web compromises.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT18",
                "mitre_id": "G0026",
                "alias": "Dynamite, TG-5418, Thedeveloper, Threat Group-0416",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Aerospace, Defense, Healthcare, Media, Tech",
                "target_geo": "US, Europe, Japan, Korea",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1105 - Ingress Tool Transfer",
                "associated_malware": "WECO, LIME, SPACESHIP",
                "associated_tools": "Metasploit, POS malware",
                "first_observed": "2009",
                "description": "Chinese actor targeting aerospace, defense, and healthcare sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT27",
                "mitre_id": "G0015",
                "alias": "Emissary, Zinc, TG-3390, Iron Tiger, Group 35",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Tech, Healthcare, Energy",
                "target_geo": "US, Europe, Middle East, Asia",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery, T1078 - Valid Accounts",
                "associated_malware": "Sysupdate, Chrome-eb, Sysprint",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2010",
                "description": "Chinese state-sponsored espionage group targeting government and technology sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT30",
                "mitre_id": "G0013",
                "alias": "Betraylotron, Cycelflx, ZINC",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Media",
                "target_geo": "Southeast Asia, US, Europe",
                "ttps": "T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1005 - Data from Local System, T1041 - Exfiltration Over C2",
                "associated_malware": "APT30, BACKSPACE",
                "associated_tools": "Custom RATs",
                "first_observed": "2010",
                "description": "Chinese state-sponsored group with long-standing operations. Part of APT1/APT2 complex.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT40",
                "mitre_id": "G0065",
                "alias": "Kryptonite, FEATURECREEK, Leviathan, TEMP.Periscope",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Aerospace, Maritime, Education, Research",
                "target_geo": "US, Europe, Japan, India, Southeast Asia",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery",
                "associated_malware": "HTTPBrowser, SYSTEMPROFO, FINDER",
                "associated_tools": "Cobalt Strike, Metasploit, Mimikatz",
                "first_observed": "2013",
                "description": "Chinese PLA-linked group targeting maritime and defense industrial sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT15",
                "mitre_id": "G0013",
                "alias": "Vixen, Karkata, Stream Cyn, RAZORBACK",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Technology",
                "target_geo": "US, Middle East, Europe",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "NDisk, Aldi, BEACON, KEYDOWN",
                "associated_tools": "Cobalt Strike, Mimikatz",
                "first_observed": "2011",
                "description": "Chinese MSS-linked group. Targets government and energy sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "China": [
            {
                "name": "APT17",
                "mitre_id": "G0025",
                "alias": "Office 31, Honey/My, Tailgater, Deputy Dog",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Government, Think Tanks, Healthcare",
                "target_geo": "US, South Korea, Japan, Taiwan",
                "ttps": "T1566 - Phishing, T1200 - Hardware Additions, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "HyperBro, ASPXSpy, China Chopper, Tonto",
                "associated_tools": "China Chopper, Cobalt Strike",
                "first_observed": "2012",
                "description": "Chinese state-sponsored actor. Targeting defense contractors and government agencies via strategic web compromises.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT18",
                "mitre_id": "G0026",
                "alias": "Dynamite, TG-5418, Thedeveloper, Threat Group-0416",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Aerospace, Defense, Healthcare, Media, Tech",
                "target_geo": "US, Europe, Japan, Korea",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1105 - Ingress Tool Transfer",
                "associated_malware": "WECO, LIME, SPACESHIP",
                "associated_tools": "Metasploit, POS malware",
                "first_observed": "2009",
                "description": "Chinese actor targeting aerospace, defense, and healthcare sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT27",
                "mitre_id": "G0015",
                "alias": "Emissary, Zinc, TG-3390, Iron Tiger, Group 35",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Tech, Healthcare, Energy",
                "target_geo": "US, Europe, Middle East, Asia",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery, T1078 - Valid Accounts",
                "associated_malware": "Sysupdate, Chrome-eb, Sysprint",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2010",
                "description": "Chinese state-sponsored espionage group targeting government and technology sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT30",
                "mitre_id": "G0013",
                "alias": "Betraylotron, Cycelflx, ZINC",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Media",
                "target_geo": "Southeast Asia, US, Europe",
                "ttps": "T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1005 - Data from Local System, T1041 - Exfiltration Over C2",
                "associated_malware": "APT30, BACKSPACE",
                "associated_tools": "Custom RATs",
                "first_observed": "2010",
                "description": "Chinese state-sponsored group with long-standing operations. Part of APT1/APT2 complex.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT40",
                "mitre_id": "G0065",
                "alias": "Kryptonite, FEATURECREEK, Leviathan, TEMP.Periscope",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Aerospace, Maritime, Education, Research",
                "target_geo": "US, Europe, Japan, India, Southeast Asia",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery",
                "associated_malware": "HTTPBrowser, SYSTEMPROFO, FINDER",
                "associated_tools": "Cobalt Strike, Metasploit, Mimikatz",
                "first_observed": "2013",
                "description": "Chinese PLA-linked group targeting maritime and defense industrial sectors.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "Iran": [
            {
                "name": "MuddyWater",
                "mitre_id": "G1043",
                "alias": "MERCURY, Static Kitten, Seedworm, TEMP.Wing, UNG_8594",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Aerospace",
                "target_geo": "Middle East, US, Europe, Central Asia",
                "ttps": "T1082 - System Information Discovery, T1005 - Data from Local System, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1105 - Ingress Tool Transfer, T1078 - Valid Accounts",
                "associated_malware": "MuddyWater, POWERSTAR, SysUpdate, Bomber",
                "associated_tools": "PowerShell Empire, Cobalt Strike",
                "first_observed": "2017",
                "description": "Iranian IRGC-linked group. Targeting government, defense, and telecom sectors across Middle East and Western targets.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "APT33",
                "mitre_id": "G0064",
                "alias": "Refined Kitten, Elfin, KILLCHAIN, Parastoo, HOLMIUM",
                "actor_type": "State-sponsored",
                "motivation": "Espionage + Sabotage",
                "capabilities": "Advanced Persistent Threat, Destructive",
                "target_sectors": "Aerospace, Energy, Petrochemical, Defense",
                "target_geo": "US, Saudi Arabia, South Korea, Israel",
                "ttps": "T1486 - Data Encrypted for Impact, T1105 - Ingress Tool Transfer, T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery",
                "associated_malware": "Shamoon, Dustman, StoneDrill, Jetico, BranDong",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2013",
                "description": "Iranian IRGC-linked group. Destructive attacks on Saudi Arabia petrochemical industry. Shamoon wiper attacks.",
                "risk_level": "critical",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "Phosphorus",
                "mitre_id": "G0059",
                "alias": "APT35, Charming Kitten, Parastoo, NewsBeef, Newscaster, Magic Hound",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Media, Activists, Think Tanks",
                "target_geo": "US, Middle East, Israel, UK",
                "ttps": "T1566 - Phishing, T1078 - Valid Accounts, T1082 - System Information Discovery, T1059 - Command and Scripting Interpreter, T1005 - Data from Local System",
                "associated_malware": "DOWNLOAD, Matriarch, POWERSTAR",
                "associated_tools": "Fake social media profiles, spear phishing",
                "first_observed": "2011",
                "description": "Iranian IRGC-linked group. Social media reconnaissance and credential harvesting. Targets journalists and activists.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "APT34",
                "mitre_id": "G0049",
                "alias": "OilRig, Helix Kitten, IRN2, COBALT GYPSY",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Energy, Finance",
                "target_geo": "Middle East, US, Europe",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Karkoff, MacDownloader, GILEL, PoisonFrog",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2014",
                "description": "Iranian IRGC-linked group targeting critical infrastructure in Middle East.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "APT39",
                "mitre_id": "G0087",
                "alias": "ITG07, Chafer, Remix Kitten",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Travel, Hospitality, Academic, Telecommunications",
                "target_geo": "Iran, Asia, Africa, Europe, North America",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1082 - System Information Discovery",
                "associated_malware": "Malware variants, custom RATs",
                "associated_tools": "Custom tools",
                "first_observed": "2014",
                "description": "Iranian MOIS-linked group. Targets travel, hospitality, academic, telecom sectors for tracking individuals.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "Fox Kitten",
                "mitre_id": "G0117",
                "alias": "UNC757, Parisite, Pioneer Kitten, RUBIDIUM, Lemon Sandstorm",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Oil and Gas, Technology, Government, Defense, Healthcare",
                "target_geo": "Middle East, North Africa, Europe, Australia, North America",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Web shell tools, custom backdoors",
                "associated_tools": "Cobalt Strike, Invoke-Obfuscation",
                "first_observed": "2017",
                "description": "Iranian government-affiliated group. Targets industrial verticals including oil and gas. Multiple VPN exploits.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "CyberAv3ngers",
                "mitre_id": "G1027",
                "alias": "Soldiers of Soloman",
                "actor_type": "State-sponsored",
                "motivation": "Hacktivism, Sabotage",
                "capabilities": "PLC compromise, Defacement",
                "target_sectors": "Water, Wastewater, Energy, Food & Beverage, Healthcare",
                "target_geo": "Global",
                "ttps": "T0842 - Industrial Control System Modification, T0888 - Point and Click Analytics",
                "associated_malware": "Unitronics PLC malware",
                "associated_tools": "Unitronics PLC exploit",
                "first_observed": "2020",
                "description": "Iranian IRGC-linked group. Compromised Unitronics PLCs in water/wastewater and other sectors.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "Agrius",
                "mitre_id": "G1030",
                "alias": "Pink Sandstorm, AMERICIUM, Agonizing Serpens, BlackShadow",
                "actor_type": "State-sponsored",
                "motivation": "Ransomware, Wiper, Sabotage",
                "capabilities": "Destructive Malware, Ransomware",
                "target_sectors": "Government, Energy, Finance",
                "target_geo": "Middle East, Israel",
                "ttps": "T1486 - Data Encrypted for Impact, T1490 - Inhibit System Recovery, T1566 - Phishing",
                "associated_malware": "Agrius ransomware, destructive wiper",
                "associated_tools": "Custom tools",
                "first_observed": "2020",
                "description": "Iranian MOIS-linked group. Ransomware and wiper operations with emphasis on Israeli targets.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "CURIUM",
                "mitre_id": "G1012",
                "alias": "Crimson Sandstorm, TA456, Tortoise Shell, Yellow Liderc",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "IT Service Providers, Government",
                "target_geo": "Middle East",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Custom malware, Mimikatz",
                "associated_tools": "Social engineering, custom tools",
                "first_observed": "2018",
                "description": "Iranian threat group targeting IT service providers. Patient social engineering over months.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "APT42",
                "mitre_id": "G1044",
                "alias": "APT42",
                "actor_type": "State-sponsored",
                "motivation": "Espionage, Surveillance",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Media, Activists",
                "target_geo": "Middle East, global",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery",
                "associated_malware": "PINEFLOWER, custom Android malware",
                "associated_tools": "Spear phishing, mobile malware",
                "first_observed": "2015",
                "description": "Iranian-sponsored threat group. Cyber espionage and surveillance. Overlaps with Magic Hound.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
        ],
        "North Korea": [
            {
                "name": "Lazarus Group",
                "mitre_id": "G0032",
                "alias": "Hidden Cobra, Zinc, Guardians of the Peace, Labyrinth Chollima, NICKEL ACADEMY",
                "actor_type": "State-sponsored",
                "motivation": "Financial + Espionage",
                "capabilities": "Advanced Persistent Threat, Destructive",
                "target_sectors": "Finance, Cryptocurrency, Defense, Government",
                "target_geo": "Global, focus on US/Asia",
                "ttps": "T1200 - Hardware Additions, T1486 - Data Encrypted for Impact, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1566 - Phishing, T1041 - Exfiltration Over C2, T1489 - Service Stop",
                "associated_malware": "WannaCry, FASTCash, COVERTCLOW, HOPLIGHT, DRATzarus, ElectricSimp",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2009",
                "description": "North Korean RGB-linked group. Cryptocurrency exchanges, banking heists. WannaCry global ransomware. Sony Pictures attack 2014.",
                "risk_level": "critical",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "Kimsuky",
                "mitre_id": "G0094",
                "alias": "Thallium, Velvet Chollima, Black Banshee, KU990, APT43, Emerald Sleet",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Academia, Think Tanks, Media, Policy",
                "target_geo": "South Korea, US, Japan, Russia, Europe",
                "ttps": "T1566 - Phishing, T1083 - File and Directory Discovery, T1082 - System Information Discovery, T1078 - Valid Accounts, T1059 - Command and Scripting Interpreter",
                "associated_malware": "GoldDragon, BabyMan, AppleJeus, Yeoreok, Tapa, ROKRAT",
                "associated_tools": "Custom RATs, Google Drive C2",
                "first_observed": "2012",
                "description": "North Korean RGB-linked espionage group. Targets South Korean policy makers, academics, journalists. 2014 Korea Hydro attack.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "Andariel",
                "mitre_id": "G0138",
                "alias": "Silent Chollima, PLUTONIUM, Onyx Sleet",
                "actor_type": "State-sponsored",
                "motivation": "Espionage + Financial",
                "capabilities": "Advanced Persistent Threat, Destructive",
                "target_sectors": "Defense, Gaming, Cryptocurrency, Government",
                "target_geo": "South Korea, US, Japan",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1190 - Exploit Public-Facing Application, T1078 - Valid Accounts",
                "associated_malware": "Andariel, Nemin, LobDong, Proligent",
                "associated_tools": "Cobalt Strike, PoisonIvy",
                "first_observed": "2009",
                "description": "North Korean RGB sub-group. Destructive attacks against South Korea. ATM and crypto theft operations.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "Vietnam": [
            {
                "name": "APT32",
                "mitre_id": "G0050",
                "alias": "OceanLotus, SeaLotus, APT-C-00, Canvas Cyclone, BISMUTH",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Business, Activists, Media",
                "target_geo": "Southeast Asia, US, Europe, India",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery, T1078 - Valid Accounts",
                "associated_malware": "Korplug, Denis, Monsoon, ShadowPad",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2014",
                "description": "Vietnamese MSS-linked group. Targets foreign governments, dissidents, businesses. Strategic web compromises.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "APT5",
                "mitre_id": "G1023",
                "alias": "Mulberry Typhoon, MANGANESE, BRONZE FLEETWOOD, Keyhole Panda",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Aerospace, Defense, Government, Tech, Telecom",
                "target_geo": "US, Europe, Asia",
                "ttps": "T1566 - Phishing, T1190 - Exploit Public-Facing Application, T1059 - Command and Scripting Interpreter",
                "associated_malware": "HTTPBrowser, Tonto",
                "associated_tools": "Cobalt Strike, Metasploit, Zero-day exploits",
                "first_observed": "2007",
                "description": "Vietnamese-linked group targeting aerospace and defense sectors with advanced tradecraft.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "USA": [
            {
                "name": "Equation Group",
                "mitre_id": "G0020",
                "alias": "Equation Editor, ESTEEM-EASTER",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat, Zero-day",
                "target_sectors": "Government, Finance, Energy, Nuclear",
                "target_geo": "Global",
                "ttps": "T1059 - Command and Scripting Interpreter, T1106 - Native API, T1083 - File Discovery, T1005 - Data from Local System, T1041 - Exfiltration Over C2",
                "associated_malware": "Stuxnet, Duqu, Flame, Gauss, Fanny",
                "first_observed": "2001",
                "description": "US NSA-linked group. Extremely sophisticated zero-day exploits. Created Stuxnet (Iran nuclear), Flame, Duqu.",
                "risk_level": "critical",
                "country_region": "North America",
                "active": 1,
            },
            {
                "name": "FruityArmor",
                "alias": "Equation Group sub-group",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Energy, Tech",
                "target_geo": "Middle East",
                "ttps": "T1059 - Command and Scripting Interpreter, T1106 - Native API, T1083 - File Discovery",
                "associated_malware": "Equation Group variants",
                "first_observed": "2012",
                "description": "US NSA sub-group targeting Middle Eastern governments.",
                "risk_level": "critical",
                "country_region": "North America",
                "active": 0,
            },
        ],
        "Israel": [
            {
                "name": "8200 Unit",
                "alias": "Unit 8200, Central Collection Command",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Tech",
                "target_geo": "Middle East, Global",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "Duqu, Flame (alleged), custom tools",
                "first_observed": "1952",
                "description": "Israeli signals intelligence unit. Elite cyber capabilities. Alleged involvement in Stuxnet development.",
                "risk_level": "critical",
                "country_region": "MEA",
                "active": 1,
            },
        ],
        "Pakistan": [
            {
                "name": "APT36",
                "alias": "Fancy Bear (misattribution), Transparent Tribe, Mythic Leopard",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Healthcare, Education",
                "target_geo": "India, US, UK, Afghanistan",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery, T1078 - Valid Accounts",
                "associated_malware": "Crimson RAT, Tonto, Moby",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2016",
                "description": "Pakistani state-sponsored group. Targets Indian government, military, and healthcare.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "Turkey": [
            {
                "name": "Sea Turtle",
                "mitre_id": "G0045",
                "alias": "Sea Turtle, Threat Group-0442",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Media, Telecom",
                "target_geo": "Middle East, Europe, US",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1082 - System Information Discovery",
                "associated_malware": "Scalable, LightNeuron",
                "associated_tools": "Custom RATs",
                "first_observed": "2018",
                "description": "Turkish state-sponsored group. DNS hijacking for espionage targeting governments and telecom.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
        ],
        "Brazil": [
            {
                "name": "Operacao Lava Jato",
                "alias": "Brazilian Hacker Group",
                "actor_type": "Criminal",
                "motivation": "Financial + Political",
                "capabilities": "Organized crime",
                "target_sectors": "Government, Finance, Energy",
                "target_geo": "Brazil, Latin America",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter",
                "associated_malware": "Trojan variants",
                "first_observed": "2014",
                "description": "Brazilian criminal group involved in political espionage and financial fraud.",
                "risk_level": "medium",
                "country_region": "South America",
                "active": 0,
            },
        ],
        "Belarus": [
            {
                "name": "GhostWriter",
                "mitre_id": "G0072",
                "alias": "UNC1151, Storm-0257",
                "actor_type": "State-sponsored",
                "motivation": "Espionage + Influence",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Media, Defense",
                "target_geo": "Ukraine, Poland, Baltic States",
                "ttps": "T1566 - Phishing, T1078 - Valid Accounts, T1588 - Obtain Capabilities",
                "associated_malware": "CredChopper, HtmlHelper",
                "associated_tools": "Phishing kits",
                "first_observed": "2017",
                "description": "Belarus-linked group (UNC1151). Political influence operations and credential theft in Eastern Europe.",
                "risk_level": "high",
                "country_region": "EMEA",
                "active": 1,
            },
        ],
        "UAE": [
            {
                "name": "Stealth Falcon",
                "alias": "Fractured Badger, Project Raven",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Media, Activists, Dissidents",
                "target_geo": "Middle East, US, UK",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts",
                "associated_malware": "DarkMatter, Stealth Falcon RAT",
                "associated_tools": "Cobalt Strike",
                "first_observed": "2015",
                "description": "UAE-linked mercenary group. Former NSA operators targeting journalists and activists.",
                "risk_level": "high",
                "country_region": "MEA",
                "active": 1,
            },
            {
                "name": "KHyper",
                "alias": "KHyper",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense",
                "target_geo": "Middle East",
                "ttps": "T1190 - Exploit Public-Facing Application, T1566 - Phishing",
                "associated_malware": "KHyper",
                "first_observed": "2019",
                "description": "UAE state-sponsored group targeting government entities in Middle East.",
                "risk_level": "medium",
                "country_region": "MEA",
                "active": 1,
            },
        ],
        "India": [
            {
                "name": "SideCopy",
                "alias": "Transparent Tribe sub-group, APT36",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Defense, Foreign Policy",
                "target_geo": "Pakistan, Afghanistan, China",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1105 - Ingress Tool Transfer",
                "associated_malware": "Crimson RAT, Parallax RAT",
                "associated_tools": "Metasploit",
                "first_observed": "2018",
                "description": "Indian state-sponsored group. Similar to Transparent Tribe, targeting Pakistani military.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
        "Syria": [
            {
                "name": "Syrian Electronic Army",
                "alias": "SEA",
                "actor_type": "Hacktivist",
                "motivation": "Hacktivism + Pro-government",
                "capabilities": "DDoS, Defacement, Phishing",
                "target_sectors": "Media, Government, NGOs",
                "target_geo": "Global",
                "ttps": "T1566 - Phishing, T1498 - Network Denial of Service, T1486 - Data Encrypted for Impact",
                "associated_malware": "SEA custom tools",
                "first_observed": "2011",
                "description": "Pro-Syrian government hacktivist group. DDoS and social media targeting.",
                "risk_level": "medium",
                "country_region": "MEA",
                "active": 0,
            },
        ],
        "North Korea": [
            {
                "name": "Lazarus Group",
                "alias": "Hidden Cobra, Zinc, Guardians of the Peace, Labyrinth Chollima",
                "actor_type": "State-sponsored",
                "motivation": "Financial + Espionage",
                "capabilities": "Advanced Persistent Threat, Destructive",
                "target_sectors": "Finance, Cryptocurrency, Defense, Government",
                "target_geo": "Global, focus on US/Asia",
                "ttps": "T1200 - Hardware Additions, T1486 - Data Encrypted for Impact, T1059 - Command and Scripting Interpreter, T1078 - Valid Accounts, T1566 - Phishing, T1041 - Exfiltration Over C2, T1489 - Service Stop",
                "associated_malware": "WannaCry, FASTCash, COVERTCLOW, HOPLIGHT, DRATzarus, ElectricSimp",
                "associated_tools": "Cobalt Strike, Metasploit",
                "first_observed": "2009",
                "description": "North Korean Reconnaissance General Bureau (RGB)-linked group. Cryptocurrency exchanges, banking heists. WannaCry global ransomware.",
                "risk_level": "critical",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "Kimsuky",
                "alias": "Thallium, Velvet Chollima, Black Banshee, KU990",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Academia, Think Tanks, Media, Policy",
                "target_geo": "South Korea, US, Japan, Russia",
                "ttps": "T1566 - Phishing, T1083 - File and Directory Discovery, T1082 - System Information Discovery, T1078 - Valid Accounts, T1059 - Command and Scripting Interpreter",
                "associated_malware": "GoldDragon, BabyMan, AppleJeus, Yeoreok, Tapa",
                "associated_tools": "Custom RATs, Google Drive C2",
                "first_observed": "2012",
                "description": "North Korean RGB-linked espionage group. Targets South Korean policy makers, academics, journalists.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "Andariel",
                "alias": "Silent Chollima, Stonefly",
                "actor_type": "State-sponsored",
                "motivation": "Espionage + Financial",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Defense, Gaming, Cryptocurrency, Government",
                "target_geo": "South Korea, US, Japan",
                "ttps": "T1566 - Phishing, T1059 - Command and Scripting Interpreter, T1190 - Exploit Public-Facing Application, T1078 - Valid Accounts",
                "associated_malware": "Andariel, Nemin, LobDong, Proligent",
                "associated_tools": "Cobalt Strike, PoisonIvy",
                "first_observed": "2015",
                "description": "North Korean unit targeting defense contractors and cryptocurrency platforms.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
            {
                "name": "KimSukky",
                "alias": "Thallium sub-group, Semi-Advanced",
                "actor_type": "State-sponsored",
                "motivation": "Espionage",
                "capabilities": "Advanced Persistent Threat",
                "target_sectors": "Government, Policy, Think Tanks",
                "target_geo": "South Korea, US",
                "ttps": "T1566 - Phishing, T1005 - Data from Local System, T1082 - System Information Discovery",
                "associated_malware": "BabyMan variant, ROKRAT",
                "associated_tools": "Spear phishing",
                "first_observed": "2017",
                "description": "Sub-group of Kimsuky targeting South Korean entities.",
                "risk_level": "high",
                "country_region": "APAC",
                "active": 1,
            },
        ],
    }

    # Default activities for tracking current threats
    # Sources: CISA, Mandiant, Recorded Future, MITRE, US-CERT, security vendor reports
    DEFAULT_ACTIVITIES = [
        # APT29 (Russia) - SolarWinds aftermath continuing
        {
            "actor_pattern": "APT29",
            "timestamp": "2025-06-15",
            "activity_type": "supply_chain_compromise",
            "description": "Targeting software supply chains via compromised update mechanisms",
            "target": "Government agencies, tech vendors",
            "severity": "critical",
            "source": "CISA AA25-109A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa25-109a",
        },
        {
            "actor_pattern": "APT29",
            "timestamp": "2025-11-20",
            "activity_type": "spear_phishing",
            "description": "Credential harvesting campaigns targeting NGOs",
            "target": "Think tanks, NGOs",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/apt29-spear-phishing-campaigns",
        },
        {
            "actor_pattern": "APT29",
            "timestamp": "2026-01-10",
            "activity_type": "brute_force",
            "description": "Password spray against Microsoft 365",
            "target": "US government contractors",
            "severity": "high",
            "source": "Microsoft Threat Intelligence",
            "source_url": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-security-incident-response",
        },
        # APT28 (Russia) - Election targeting
        {
            "actor_pattern": "APT28",
            "timestamp": "2025-08-12",
            "activity_type": "spear_phishing",
            "description": "Phishing with fake travel itineraries targeting NATO diplomats",
            "target": "NATO diplomats",
            "severity": "critical",
            "source": "CISA AA25-195A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa25-195a",
        },
        {
            "actor_pattern": "APT28",
            "timestamp": "2025-10-05",
            "activity_type": "web_compromise",
            "description": "Strategic web compromise of news sites targeting Ukraine",
            "target": "Ukraine, Georgia",
            "severity": "high",
            "source": "Recorded Future",
            "source_url": "https://www.recordedfuture.com/research/apt28-operations",
        },
        # Sandworm (Russia) - Critical infrastructure
        {
            "actor_pattern": "Sandworm Team",
            "timestamp": "2025-04-22",
            "activity_type": "destructive_attack",
            "description": "Wiper malware targeting energy sector",
            "target": "Ukrainian energy grid",
            "severity": "critical",
            "source": "CERT-UA",
            "source_url": "https://cert.gov.ua/articles/u-a-poshkodzhenni-ta-znyshchennia-danikh-na-terytoriji-ukrajiny",
        },
        {
            "actor_pattern": "Sandworm Team",
            "timestamp": "2025-07-18",
            "activity_type": "network_exploitation",
            "description": "VPN vulnerabilities exploitation targeting European governments",
            "target": "European government networks",
            "severity": "critical",
            "source": "CISA AA25-201A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa25-201a",
        },
        {
            "actor_pattern": "Sandworm Team",
            "timestamp": "2026-02-01",
            "activity_type": "destructive_attack",
            "description": "Cyclops Blink botnet deployment",
            "target": "Ukrainian networks",
            "severity": "critical",
            "source": "US-CERT AA22-110A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa22-110a",
        },
        # Turla (Russia)
        {
            "actor_pattern": "Turla",
            "timestamp": "2025-09-14",
            "activity_type": "espionage",
            "description": "Satellite C2 infrastructure updates",
            "target": "EU government agencies",
            "severity": "critical",
            "source": "Kaspersky Securelist",
            "source_url": "https://securelist.com/turla-apt/105140/",
        },
        # Dragonfly (Russia)
        {
            "actor_pattern": "Dragonfly",
            "timestamp": "2025-06-30",
            "activity_type": "supply_chain",
            "description": "Compromised software vendor websites for ICS targeting",
            "target": "Energy sector, ICS",
            "severity": "critical",
            "source": "Dragos",
            "source_url": "https://www.dragos.com/blog/threat-reports/dragonfly-2-0-three-years-later",
        },
        # APT41 (China) - Healthcare targeting
        {
            "actor_pattern": "APT41",
            "timestamp": "2025-05-08",
            "activity_type": "supply_chain",
            "description": "Compromised gaming software for supply chain attacks",
            "target": "Healthcare, pharma",
            "severity": "critical",
            "source": "CISA AA24-109A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-109a",
        },
        {
            "actor_pattern": "APT41",
            "timestamp": "2025-08-25",
            "activity_type": "spear_phishing",
            "description": "Fake job postings delivering malware to tech companies",
            "target": "Tech companies",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/apt41-global-operations",
        },
        {
            "actor_pattern": "APT41",
            "timestamp": "2025-11-30",
            "activity_type": "exploit",
            "description": "Zero-day exploitation of edge devices",
            "target": "Telecom providers",
            "severity": "critical",
            "source": "Recorded Future",
            "source_url": "https://www.recordedfuture.com/threat-intel/groups/apt41",
        },
        # APT10 (China) - MSP targeting
        {
            "actor_pattern": "APT10",
            "timestamp": "2025-06-20",
            "activity_type": "supply_chain",
            "description": "Targeting managed service providers",
            "target": "Managed service providers",
            "severity": "high",
            "source": "CISA AA24-241A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-241a",
        },
        # APT17 (China)
        {
            "actor_pattern": "APT17",
            "timestamp": "2025-07-10",
            "activity_type": "spear_phishing",
            "description": "Defense contractor targeting",
            "target": "US defense contractors",
            "severity": "high",
            "source": "US Department of Justice",
            "source_url": "https://www.justice.gov/opa/pr/two-chinese-intelligence-officers-and-six-hackers-charged-cyber-offenses",
        },
        # APT27 (China)
        {
            "actor_pattern": "APT27",
            "timestamp": "2025-10-12",
            "activity_type": "spear_phishing",
            "description": "Government employee targeting in South Asia",
            "target": "South Asian governments",
            "severity": "high",
            "source": "Palo Alto Unit 42",
            "source_url": "https://unit42.paloaltonetworks.com/apt27-operations/",
        },
        # APT40 (China)
        {
            "actor_pattern": "APT40",
            "timestamp": "2025-08-05",
            "activity_type": "espionage",
            "description": "Maritime research institution targeting",
            "target": "Maritime institutes",
            "severity": "high",
            "source": "CISA AA24-038A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-038a",
        },
        # MuddyWater (Iran)
        {
            "actor_pattern": "MuddyWater",
            "timestamp": "2025-05-15",
            "activity_type": "spear_phishing",
            "description": "Targeting Kurdish activists and dissidents",
            "target": "Middle East activists",
            "severity": "high",
            "source": "Microsoft Threat Intelligence",
            "source_url": "https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/muddywater",
        },
        {
            "actor_pattern": "MuddyWater",
            "timestamp": "2025-09-20",
            "activity_type": "exploit",
            "description": "VPN exploitation campaigns against government agencies",
            "target": "Government agencies",
            "severity": "critical",
            "source": "CISA AA24-317A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-317a",
        },
        # APT33 (Iran) - Destructive
        {
            "actor_pattern": "APT33",
            "timestamp": "2025-06-25",
            "activity_type": "destructive_attack",
            "description": "Shamoon wiper preparation targeting Saudi petrochemical",
            "target": "Saudi petrochemical",
            "severity": "critical",
            "source": "CISA AA23-353A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-353a",
        },
        {
            "actor_pattern": "APT33",
            "timestamp": "2025-11-10",
            "activity_type": "spear_phishing",
            "description": "Aerospace sector targeting",
            "target": "US aerospace",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/apt33-apt34-iranian-operations",
        },
        # Phosphorus (Iran)
        {
            "actor_pattern": "Phosphorus",
            "timestamp": "2025-07-30",
            "activity_type": "spear_phishing",
            "description": "Fake invite to conference targeting journalists",
            "target": "Journalists, activists",
            "severity": "high",
            "source": "Google TAG",
            "source_url": "https://blog.google/threat-analysis-group/iranian-threat-actor-apt42-targets-groups-in-middle-east",
        },
        # Fox Kitten (Iran)
        {
            "actor_pattern": "Fox Kitten",
            "timestamp": "2025-08-15",
            "activity_type": "exploit",
            "description": "VPN exploitation targeting oil and gas sector",
            "target": "Oil and gas, critical infrastructure",
            "severity": "critical",
            "source": "Dragos",
            "source_url": "https://www.dragos.com/blog/threat-reports/iranian-concern",
        },
        # Lazarus (North Korea) - Crypto
        {
            "actor_pattern": "Lazarus Group",
            "timestamp": "2025-04-10",
            "activity_type": "financial_theft",
            "description": "Cryptocurrency exchange hack",
            "target": "Asian exchanges",
            "severity": "critical",
            "source": "Kakao Enterprise",
            "source_url": "https://www.kakaoenterprise.com/blog",
        },
        {
            "actor_pattern": "Lazarus Group",
            "timestamp": "2025-08-15",
            "activity_type": "supply_chain",
            "description": "Supply chain via npm packages targeting crypto developers",
            "target": "Crypto developers",
            "severity": "critical",
            "source": "ReversingLabs",
            "source_url": "https://www.reversinglabs.com/blog/lazarus-malware-npm-packages",
        },
        {
            "actor_pattern": "Lazarus Group",
            "timestamp": "2025-12-05",
            "activity_type": "spear_phishing",
            "description": "Fake job interviews targeting crypto employees",
            "target": "Crypto employees",
            "severity": "critical",
            "source": "CISA AA24-176A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-176a",
        },
        # Kimsuky (North Korea)
        {
            "actor_pattern": "Kimsuky",
            "timestamp": "2025-06-08",
            "activity_type": "spear_phishing",
            "description": "Korean peninsula policy experts targeting",
            "target": "South Korean academia",
            "severity": "high",
            "source": "CISA AA24-134A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-134a",
        },
        # APT38 (North Korea)
        {
            "actor_pattern": "APT38",
            "timestamp": "2025-09-25",
            "activity_type": "financial_theft",
            "description": "ATM cash-out operations targeting banks globally",
            "target": "Financial institutions",
            "severity": "critical",
            "source": "US Treasury FinCEN",
            "source_url": "https://www.fincen.gov/news/news-releases/financial-institutions-face-increased-cyber-threat-north-korean-apt38",
        },
        # APT32 (Vietnam)
        {
            "actor_pattern": "APT32",
            "timestamp": "2025-07-22",
            "activity_type": "espionage",
            "description": "Business intelligence targeting dissidents and activists",
            "target": "Vietnam business critics, media",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/apt32-sea-lotus-operations",
        },
        # Fin7 (Russia)
        {
            "actor_pattern": "Fin7",
            "timestamp": "2025-10-18",
            "activity_type": "financial_fraud",
            "description": "POS malware deployment targeting retail chains",
            "target": "Retail chains",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/fin7-pose-threat-finance-retail",
        },
        # SideCopy (India)
        {
            "actor_pattern": "SideCopy",
            "timestamp": "2025-05-20",
            "activity_type": "spear_phishing",
            "description": "Healthcare sector phishing campaign targeting Indian institutions",
            "target": "Indian healthcare",
            "severity": "high",
            "source": "CERT-In",
            "source_url": "https://www.cert-in.org.in/",
        },
        # Sea Turtle (Turkey)
        {
            "actor_pattern": "Sea Turtle",
            "timestamp": "2025-08-30",
            "activity_type": "dns_hijacking",
            "description": "DNS hijacking for credential harvesting",
            "target": "Telecom providers, governments",
            "severity": "critical",
            "source": "CISA AA24-093A",
            "source_url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-093a",
        },
        # GhostWriter (Belarus)
        {
            "actor_pattern": "GhostWriter",
            "timestamp": "2025-09-05",
            "activity_type": "influence",
            "description": "Fake news site creation targeting Eastern European media",
            "target": "Eastern European media",
            "severity": "high",
            "source": "Mandiant",
            "source_url": "https://www.mandiant.com/resources/ghostwriter-update-cyber-espionage",
        },
    ]

    def __init__(self, db=None):
        self.db = db

    def initialize_default_actors(self, db):
        """Initialize default threat actors in database"""
        # First clear existing to avoid duplicates
        conn = sqlite3.connect(db.db_path)
        cursor = conn.cursor()
        cursor.execute("DELETE FROM threat_actor_activities")
        cursor.execute("DELETE FROM threat_actors")
        conn.commit()
        conn.close()

        for country, actors in self.DEFAULT_ACTORS.items():
            for actor in actors:
                actor["country"] = country
                db.add_threat_actor(actor)

        # Initialize default activities
        self._initialize_default_activities(db)

        logger.info(
            f"Initialized {sum(len(v) for v in self.DEFAULT_ACTORS.values())} threat actors"
        )

    def _initialize_default_activities(self, db):
        """Initialize default activities from database actors"""
        actors = db.get_threat_actors_by_country()
        actor_name_to_id = {a["name"]: a["id"] for a in actors}

        for activity in self.DEFAULT_ACTIVITIES:
            actor_pattern = activity.pop("actor_pattern", None)
            if actor_pattern and actor_pattern in actor_name_to_id:
                activity["actor_id"] = actor_name_to_id[actor_pattern]
                db.add_threat_actor_activity(activity)

        logger.info(f"Initialized {len(self.DEFAULT_ACTIVITIES)} default activities")

    def get_actors_by_country(self, country: str = None) -> List[Dict[str, Any]]:
        """Get threat actors by country"""
        if not self.db:
            return []
        return self.db.get_threat_actors_by_country(country)

    def get_actor_by_id(self, actor_id: str) -> Optional[Dict[str, Any]]:
        """Get specific threat actor"""
        if not self.db:
            return None
        return self.db.get_threat_actor_by_id(actor_id)

    def get_actor_activities(
        self, actor_id: str, limit: int = 50
    ) -> List[Dict[str, Any]]:
        """Get activities for a specific actor"""
        if not self.db:
            return []
        return self.db.get_threat_actor_activities(actor_id, limit)

    def get_stats(self) -> Dict[str, Any]:
        """Get threat actor statistics"""
        if not self.db:
            return {}
        return self.db.get_threat_actor_stats()

    def add_activity(self, activity: Dict[str, Any]) -> str:
        """Add new activity for an actor"""
        if not self.db:
            return ""
        return self.db.add_threat_actor_activity(activity)

    def generate_assessment(self, actor_id: str) -> Dict[str, Any]:
        """Generate threat assessment for an actor"""
        actor = self.get_actor_by_id(actor_id)
        if not actor:
            return {}

        activities = self.get_actor_activities(actor_id, limit=100)

        # Analyze recent activity
        recent_activities = [
            a
            for a in activities
            if datetime.fromisoformat(a["timestamp"].replace("Z", "+00:00"))
            > datetime.utcnow() - timedelta(days=30)
        ]

        # Calculate threat vectors based on TTPs
        ttps = actor.get("ttps", "").split(", ")

        attack_vectors = []
        for ttp in ttps:
            if "Exploit Public-Facing Application" in ttp:
                attack_vectors.append("External remote attack (VPN, web apps)")
            elif "Phishing" in ttp:
                attack_vectors.append("Credential harvesting via phishing")
            elif "Hardware" in ttp:
                attack_vectors.append("Physical access / supply chain")
            elif "Data Encrypted" in ttp:
                attack_vectors.append("Ransomware / destructive attack")

        # Project future activity
        activity_trend = "increasing"
        if len(recent_activities) < 5:
            activity_trend = "decreasing"
        elif len(recent_activities) < 10:
            activity_trend = "stable"

        risk_factors = []
        if actor.get("risk_level") == "critical":
            risk_factors.append("Historical destructive capability")
        if "financial" in actor.get("motivation", "").lower():
            risk_factors.append("Financially motivated - targeting assets")
        if "Espionage" in actor.get("motivation", ""):
            risk_factors.append("Data exfiltration focus")

        return {
            "actor": actor,
            "recent_activity_count": len(recent_activities),
            "total_activities": len(activities),
            "activity_trend": activity_trend,
            "likely_attack_vectors": attack_vectors,
            "risk_factors": risk_factors,
            "projected_threat": f"{actor.get('risk_level', 'medium').upper()} - {activity_trend} activity",
            "recommended_mitigations": self._get_mitigations(ttps),
        }

    def _get_mitigations(self, ttps: List[str]) -> List[str]:
        """Get mitigations based on TTPs"""
        mitigations = []
        for ttp in ttps:
            if "Phishing" in ttp:
                mitigations.append("Implement email filtering + user training")
            if "Exploit" in ttp:
                mitigations.append("Keep systems patched, use WAF")
            if "Hardware" in ttp:
                mitigations.append("Hardware integrity monitoring")
            if "Command" in ttp:
                mitigations.append("EDR/endpoint monitoring")
            if "Credentials" in ttp:
                mitigations.append("MFA enforcement")
        return list(set(mitigations)) if mitigations else ["Defense in depth"]


# Global instance
_threat_intel: Optional[ThreatActorIntelligence] = None


def get_threat_intelligence(db=None) -> ThreatActorIntelligence:
    """Get or create threat intelligence instance"""
    global _threat_intel
    if _threat_intel is None:
        _threat_intel = ThreatActorIntelligence(db)
    return _threat_intel
